blank_issues_enabled: false
contact_links:
  - name: PaperInk Discussions
    url: https://github.com/binbinsh/hugo-PaperInk/discussions
    about: Please ask and answer questions/doubts here, DO NOT open an issue for questions.
